" ================
" plugin loader
" ================
source ~/.dotfiles/vimrc/plugin.vim

" ================
" config section
" ================

" basic config
source ~/.dotfiles/vimrc/basic.vim

" plugin config
source ~/.dotfiles/vimrc/ros.vim
source ~/.dotfiles/vimrc/indentlines.vim
source ~/.dotfiles/vimrc/lightline.vim
source ~/.dotfiles/vimrc/ycm.vim
source ~/.dotfiles/vimrc/clang_format.vim
source ~/.dotfiles/vimrc/rooter.vim
source ~/.dotfiles/vimrc/altr.vim
source ~/.dotfiles/vimrc/unite.vim
source ~/.dotfiles/vimrc/fugitive.vim
source ~/.dotfiles/vimrc/syntastic.vim
"
" source ~/.dotfiles/vimrc/easy_motion.vim

" source ~/.dotfiles/vimrc/quickrun.vim
" source ~/.dotfiles/vimrc/closetag.vim
"
" source ~/.dotfiles/vimrc/clang.vim
" source ~/.dotfiles/vimrc/complete.vim
" source ~/.dotfiles/vimrc/jedi.vim
" source ~/.dotfiles/vimrc/neosnippet.vim
" source ~/.dotfiles/vimrc/autotags.vim
" source ~/.dotfiles/vimrc/markdown.vim

" key config
source ~/.dotfiles/vimrc/keys.vim
